/* The following code was generated by JFlex 1.3.5 on 12/9/24, 8:59 AM */

package cup.example;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.Symbol;
import java.lang.*;
import java.io.InputStreamReader;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 12/9/24, 8:59 AM from the specification file
 * <tt>file:/D:/Repo/BisonitaFinal/Project/lexer.jflex</tt>
 */
public class Lexer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int CODESEG = 1;
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\11\1\3\1\2\1\0\1\3\1\1\16\11\4\0\1\51\1\0"+
    "\1\12\1\0\1\10\1\16\2\0\1\20\1\21\1\7\1\14\1\47"+
    "\1\15\1\5\1\6\12\4\1\32\1\13\1\23\1\22\1\24\2\0"+
    "\32\10\4\0\1\10\1\0\1\25\1\10\1\41\1\26\1\36\1\40"+
    "\1\34\1\45\1\42\2\10\1\44\1\35\1\17\1\27\1\33\1\10"+
    "\1\30\1\43\1\31\1\37\1\50\1\46\3\10\4\0\41\11\2\0"+
    "\4\10\4\0\1\10\2\0\1\11\7\0\1\10\4\0\1\10\5\0"+
    "\27\10\1\0\37\10\1\0\u01ca\10\4\0\14\10\16\0\5\10\7\0"+
    "\1\10\1\0\1\10\21\0\160\11\5\10\1\0\2\10\2\0\4\10"+
    "\1\0\1\10\6\0\1\10\1\0\3\10\1\0\1\10\1\0\24\10"+
    "\1\0\123\10\1\0\213\10\1\0\5\11\2\0\246\10\1\0\46\10"+
    "\2\0\1\10\6\0\51\10\6\0\1\10\1\0\55\11\1\0\1\11"+
    "\1\0\2\11\1\0\2\11\1\0\1\11\10\0\33\10\4\0\4\10"+
    "\15\0\6\11\5\0\1\10\4\0\13\11\1\0\1\11\3\0\53\10"+
    "\37\11\4\0\2\10\1\11\143\10\1\0\1\10\10\11\1\0\6\11"+
    "\2\10\2\11\1\0\4\11\2\10\12\11\3\10\2\0\1\10\17\0"+
    "\1\11\1\10\1\11\36\10\33\11\2\0\131\10\13\11\1\10\16\0"+
    "\12\11\41\10\11\11\2\10\4\0\1\10\2\0\1\11\30\10\4\11"+
    "\1\10\11\11\1\10\3\11\1\10\5\11\22\0\31\10\3\11\4\0"+
    "\13\10\5\0\30\10\1\0\6\10\1\0\2\11\6\0\10\11\52\10"+
    "\72\11\66\10\3\11\1\10\22\11\1\10\7\11\12\10\2\11\2\0"+
    "\12\11\1\0\20\10\3\11\1\0\10\10\2\0\2\10\2\0\26\10"+
    "\1\0\7\10\1\0\1\10\3\0\4\10\2\0\1\11\1\10\7\11"+
    "\2\0\2\11\2\0\3\11\1\10\10\0\1\11\4\0\2\10\1\0"+
    "\3\10\2\11\2\0\12\11\4\10\7\0\2\10\1\0\1\11\2\0"+
    "\3\11\1\0\6\10\4\0\2\10\2\0\26\10\1\0\7\10\1\0"+
    "\2\10\1\0\2\10\1\0\2\10\2\0\1\11\1\0\5\11\4\0"+
    "\2\11\2\0\3\11\3\0\1\11\7\0\4\10\1\0\1\10\7\0"+
    "\14\11\3\10\1\11\13\0\3\11\1\0\11\10\1\0\3\10\1\0"+
    "\26\10\1\0\7\10\1\0\2\10\1\0\5\10\2\0\1\11\1\10"+
    "\10\11\1\0\3\11\1\0\3\11\2\0\1\10\17\0\2\10\2\11"+
    "\2\0\12\11\1\0\1\10\7\0\1\10\6\11\1\0\3\11\1\0"+
    "\10\10\2\0\2\10\2\0\26\10\1\0\7\10\1\0\2\10\1\0"+
    "\5\10\2\0\1\11\1\10\7\11\2\0\2\11\2\0\3\11\7\0"+
    "\3\11\4\0\2\10\1\0\3\10\2\11\2\0\12\11\1\0\1\10"+
    "\20\0\1\11\1\10\1\0\6\10\3\0\3\10\1\0\4\10\3\0"+
    "\2\10\1\0\1\10\1\0\2\10\3\0\2\10\3\0\3\10\3\0"+
    "\14\10\4\0\5\11\3\0\3\11\1\0\4\11\2\0\1\10\6\0"+
    "\1\11\16\0\12\11\11\0\1\10\6\0\5\11\10\10\1\0\3\10"+
    "\1\0\27\10\1\0\20\10\2\0\1\11\1\10\7\11\1\0\3\11"+
    "\1\0\4\11\7\0\2\11\1\0\3\10\2\0\1\10\2\0\2\10"+
    "\2\11\2\0\12\11\20\0\1\10\3\11\1\0\10\10\1\0\3\10"+
    "\1\0\27\10\1\0\12\10\1\0\5\10\2\0\1\11\1\10\7\11"+
    "\1\0\3\11\1\0\4\11\7\0\2\11\6\0\2\10\1\0\2\10"+
    "\2\11\2\0\12\11\1\0\2\10\1\11\14\0\4\11\11\10\1\0"+
    "\3\10\1\0\51\10\2\11\1\10\7\11\1\0\3\11\1\0\4\11"+
    "\1\10\5\0\3\10\1\11\7\0\3\10\2\11\2\0\12\11\12\0"+
    "\6\10\1\0\3\11\1\0\22\10\3\0\30\10\1\0\11\10\1\0"+
    "\1\10\2\0\7\10\3\0\1\11\4\0\6\11\1\0\1\11\1\0"+
    "\10\11\6\0\12\11\2\0\2\11\15\0\60\10\1\11\2\10\7\11"+
    "\4\0\10\10\10\11\1\0\12\11\47\0\2\10\1\0\1\10\1\0"+
    "\5\10\1\0\30\10\1\0\1\10\1\0\12\10\1\11\2\10\11\11"+
    "\1\10\2\0\5\10\1\0\1\10\1\0\7\11\1\0\12\11\2\0"+
    "\4\10\40\0\1\10\27\0\2\11\6\0\12\11\13\0\1\11\1\0"+
    "\1\11\1\0\1\11\4\0\2\11\10\10\1\0\44\10\4\0\24\11"+
    "\1\0\2\11\5\10\13\11\1\0\44\11\11\0\1\11\71\0\53\10"+
    "\24\11\1\10\12\11\6\0\6\10\4\11\4\10\3\11\1\10\3\11"+
    "\2\10\7\11\3\10\4\11\15\10\14\11\1\10\17\11\2\0\46\10"+
    "\1\0\1\10\5\0\1\10\2\0\53\10\1\0\u014d\10\1\0\4\10"+
    "\2\0\7\10\1\0\1\10\1\0\4\10\2\0\51\10\1\0\4\10"+
    "\2\0\41\10\1\0\4\10\2\0\7\10\1\0\1\10\1\0\4\10"+
    "\2\0\17\10\1\0\71\10\1\0\4\10\2\0\103\10\2\0\3\11"+
    "\40\0\20\10\20\0\126\10\2\0\6\10\3\0\u026c\10\2\0\21\10"+
    "\1\0\32\10\5\0\113\10\3\0\13\10\7\0\22\10\4\11\11\0"+
    "\23\10\3\11\13\0\22\10\2\11\14\0\15\10\1\0\3\10\1\0"+
    "\2\11\14\0\64\10\40\11\3\0\1\10\3\0\2\10\1\11\2\0"+
    "\12\11\41\0\17\11\6\0\131\10\7\0\5\10\2\11\42\10\1\11"+
    "\1\10\5\0\106\10\12\0\37\10\1\0\14\11\4\0\14\11\12\0"+
    "\12\11\36\10\2\0\5\10\13\0\54\10\4\0\32\10\6\0\12\11"+
    "\46\0\27\10\5\11\4\0\65\10\12\11\1\0\35\11\2\0\13\11"+
    "\6\0\12\11\15\0\1\10\10\0\16\11\1\0\20\11\61\0\5\11"+
    "\57\10\21\11\10\10\3\0\12\11\21\0\11\11\14\0\3\11\36\10"+
    "\15\11\2\10\12\11\54\10\16\11\14\0\44\10\24\11\10\0\12\11"+
    "\3\0\3\10\12\11\44\10\2\0\11\10\7\0\53\10\2\0\3\10"+
    "\20\0\3\11\1\0\25\11\4\10\1\11\6\10\1\11\2\10\3\11"+
    "\1\10\5\0\300\10\100\11\u0116\10\2\0\6\10\2\0\46\10\2\0"+
    "\6\10\2\0\10\10\1\0\1\10\1\0\1\10\1\0\1\10\1\0"+
    "\37\10\2\0\65\10\1\0\7\10\1\0\1\10\3\0\3\10\1\0"+
    "\7\10\3\0\4\10\2\0\6\10\4\0\15\10\5\0\3\10\1\0"+
    "\7\10\16\0\5\11\32\0\5\11\20\0\2\10\23\0\1\10\13\0"+
    "\5\11\1\0\12\11\1\0\1\10\15\0\1\10\20\0\15\10\3\0"+
    "\41\10\17\0\15\11\4\0\1\11\3\0\14\11\21\0\1\10\4\0"+
    "\1\10\2\0\12\10\1\0\1\10\3\0\5\10\6\0\1\10\1\0"+
    "\1\10\1\0\1\10\1\0\4\10\1\0\13\10\2\0\4\10\5\0"+
    "\5\10\4\0\1\10\21\0\51\10\u0a77\0\345\10\6\0\4\10\3\11"+
    "\2\10\14\0\46\10\1\0\1\10\5\0\1\10\2\0\70\10\7\0"+
    "\1\10\17\0\1\11\27\10\11\0\7\10\1\0\7\10\1\0\7\10"+
    "\1\0\7\10\1\0\7\10\1\0\7\10\1\0\7\10\1\0\7\10"+
    "\1\0\40\11\57\0\1\10\u01d5\0\3\10\31\0\11\10\6\11\1\0"+
    "\5\10\2\0\5\10\4\0\126\10\2\0\2\11\2\0\3\10\1\0"+
    "\132\10\1\0\4\10\5\0\53\10\1\0\136\10\21\0\40\10\60\0"+
    "\20\10\u0200\0\u19c0\10\100\0\u568d\10\103\0\56\10\2\0\u010d\10\3\0"+
    "\20\10\12\11\2\10\24\0\57\10\1\11\4\0\12\11\1\0\37\10"+
    "\2\11\120\10\2\11\45\0\11\10\2\0\147\10\2\0\100\10\5\0"+
    "\2\10\1\0\1\10\1\0\5\10\30\0\20\10\1\11\3\10\1\11"+
    "\4\10\1\11\27\10\5\11\4\0\1\11\13\0\1\10\7\0\64\10"+
    "\14\0\2\11\62\10\22\11\12\0\12\11\6\0\22\11\6\10\3\0"+
    "\1\10\1\0\2\10\13\11\34\10\10\11\2\0\27\10\15\11\14\0"+
    "\35\10\3\0\4\11\57\10\16\11\16\0\1\10\12\11\6\0\5\10"+
    "\1\11\12\10\12\11\5\10\1\0\51\10\16\11\11\0\3\10\1\11"+
    "\10\10\2\11\2\0\12\11\6\0\27\10\3\0\1\10\3\11\62\10"+
    "\1\11\1\10\3\11\2\10\2\11\5\10\2\11\1\10\1\11\1\10"+
    "\30\0\3\10\2\0\13\10\5\11\2\0\3\10\2\11\12\0\6\10"+
    "\2\0\6\10\2\0\6\10\11\0\7\10\1\0\7\10\1\0\53\10"+
    "\1\0\16\10\6\0\163\10\10\11\1\0\2\11\2\0\12\11\6\0"+
    "\u2ba4\10\14\0\27\10\4\0\61\10\u2104\0\u016e\10\2\0\152\10\46\0"+
    "\7\10\14\0\5\10\5\0\1\10\1\11\12\10\1\0\15\10\1\0"+
    "\5\10\1\0\1\10\1\0\2\10\1\0\2\10\1\0\154\10\41\0"+
    "\u016b\10\22\0\100\10\2\0\66\10\50\0\15\10\3\0\20\11\20\0"+
    "\20\11\3\0\2\10\30\0\3\10\31\0\1\10\6\0\5\10\1\0"+
    "\207\10\2\0\1\11\4\0\1\10\13\0\12\11\7\0\32\10\4\0"+
    "\1\10\1\0\32\10\13\0\131\10\3\0\6\10\2\0\6\10\2\0"+
    "\6\10\2\0\3\10\3\0\2\10\3\0\2\10\22\0\3\11\4\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    42,    84,   126,    84,   168,   210,   252,   294,   336, 
       84,    84,    84,    84,   378,    84,    84,    84,   420,   462, 
      504,   546,   588,   630,   672,   714,   756,   798,   840,   882, 
      924,   966,  1008,    84,  1050,  1092,    84,   336,   336,  1134, 
       84,    84,    84,  1176,   294,  1218,   294,  1260,   294,  1302, 
       84,  1344,  1386,  1428,  1470,  1512,  1554,  1596,   294,  1638, 
     1680,  1722,  1764,  1050,   294,   294,  1806,  1848,  1890,  1932, 
     1974,  2016,  2058,  2100,   294,  2142,  2184,  2226,  2268,  2310, 
     2352,   294,   294,   294,  2394,   294,  2436,   294,  2478,  2520, 
     2562,  2604,   294,  2646,  2688,  2730,  2772,  2814,  2856,  2898, 
     2940,   294,  2982,  3024,  3066,   294,  3108,  3150,  3192,  3234, 
     3276,   294,   294,   294,  3318,  3360,   294,  3402,  3444,  3486, 
      294,  3528,  3570,   294,  3612,  3654,  3696,   294,  3738,  3780, 
     3822,  3864,   294,  3906,    84,  3948,  3990,    84,   294,  4032, 
      294
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\3\1\4\2\5\1\6\1\3\1\7\1\10\1\11"+
    "\1\3\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\11\1\34\1\35\1\11\1\36"+
    "\1\11\1\37\1\40\2\11\1\41\1\42\1\11\1\5"+
    "\52\3\54\0\1\5\53\0\1\6\1\43\52\0\1\44"+
    "\52\0\1\45\46\0\1\11\3\0\2\11\5\0\1\11"+
    "\5\0\5\11\1\0\14\11\1\0\1\11\1\0\2\46"+
    "\1\0\7\46\1\47\37\46\4\0\1\11\3\0\2\11"+
    "\5\0\1\11\5\0\2\11\1\50\2\11\1\0\14\11"+
    "\1\0\1\11\23\0\1\51\1\0\1\52\47\0\1\53"+
    "\33\0\1\11\3\0\2\11\5\0\1\54\5\0\5\11"+
    "\1\0\14\11\1\0\1\11\5\0\1\11\3\0\2\11"+
    "\5\0\1\11\5\0\2\11\1\55\1\56\1\11\1\0"+
    "\14\11\1\0\1\11\5\0\1\11\3\0\2\11\5\0"+
    "\1\11\5\0\3\11\1\57\1\11\1\0\14\11\1\0"+
    "\1\11\5\0\1\11\3\0\2\11\5\0\1\11\5\0"+
    "\5\11\1\0\3\11\1\60\10\11\1\0\1\11\5\0"+
    "\1\11\3\0\2\11\5\0\1\11\5\0\2\11\1\61"+
    "\2\11\1\0\12\11\1\62\1\11\1\0\1\11\23\0"+
    "\1\63\33\0\1\11\3\0\2\11\5\0\1\11\5\0"+
    "\3\11\1\64\1\11\1\0\14\11\1\0\1\11\5\0"+
    "\1\11\3\0\2\11\5\0\1\11\5\0\2\11\1\65"+
    "\2\11\1\0\14\11\1\0\1\11\5\0\1\11\3\0"+
    "\2\11\5\0\1\66\5\0\5\11\1\0\11\11\1\67"+
    "\2\11\1\0\1\11\5\0\1\11\3\0\2\11\5\0"+
    "\1\11\5\0\2\11\1\70\2\11\1\0\4\11\1\71"+
    "\7\11\1\0\1\11\5\0\1\11\3\0\2\11\5\0"+
    "\1\72\5\0\5\11\1\0\5\11\1\73\6\11\1\0"+
    "\1\11\5\0\1\11\3\0\2\11\5\0\1\11\5\0"+
    "\4\11\1\74\1\0\3\11\1\75\10\11\1\0\1\11"+
    "\5\0\1\11\3\0\2\11\5\0\1\11\5\0\3\11"+
    "\1\76\1\11\1\0\12\11\1\77\1\11\1\0\1\11"+
    "\5\0\1\100\45\0\1\44\1\4\1\5\47\44\4\0"+
    "\1\11\3\0\2\11\5\0\1\11\5\0\4\11\1\101"+
    "\1\0\14\11\1\0\1\11\5\0\1\11\3\0\2\11"+
    "\5\0\1\11\5\0\1\11\1\102\3\11\1\0\14\11"+
    "\1\0\1\11\5\0\1\11\3\0\2\11\5\0\1\11"+
    "\5\0\1\103\4\11\1\0\14\11\1\0\1\11\5\0"+
    "\1\11\3\0\2\11\5\0\1\11\5\0\1\104\3\11"+
    "\1\105\1\0\14\11\1\0\1\11\5\0\1\11\3\0"+
    "\2\11\5\0\1\11\5\0\5\11\1\0\3\11\1\106"+
    "\10\11\1\0\1\11\5\0\1\11\3\0\2\11\5\0"+
    "\1\11\5\0\2\11\1\107\2\11\1\0\14\11\1\0"+
    "\1\11\5\0\1\11\3\0\2\11\5\0\1\11\5\0"+
    "\5\11\1\0\14\11\1\0\1\110\5\0\1\11\3\0"+
    "\2\11\5\0\1\11\5\0\1\11\1\111\3\11\1\0"+
    "\14\11\1\0\1\11\5\0\1\11\3\0\2\11\5\0"+
    "\1\11\5\0\5\11\1\0\10\11\1\112\3\11\1\0"+
    "\1\11\5\0\1\11\3\0\2\11\5\0\1\11\5\0"+
    "\3\11\1\113\1\11\1\0\14\11\1\0\1\11\5\0"+
    "\1\11\3\0\2\11\5\0\1\114\5\0\5\11\1\0"+
    "\14\11\1\0\1\11\5\0\1\11\3\0\2\11\5\0"+
    "\1\11\5\0\4\11\1\115\1\0\14\11\1\0\1\11"+
    "\5\0\1\11\3\0\2\11\5\0\1\11\5\0\3\11"+
    "\1\116\1\11\1\0\14\11\1\0\1\11\5\0\1\11"+
    "\3\0\2\11\5\0\1\11\5\0\4\11\1\117\1\0"+
    "\14\11\1\0\1\11\5\0\1\11\3\0\2\11\5\0"+
    "\1\11\5\0\5\11\1\0\7\11\1\120\4\11\1\0"+
    "\1\11\5\0\1\11\3\0\2\11\5\0\1\11\5\0"+
    "\5\11\1\0\7\11\1\121\4\11\1\0\1\11\5\0"+
    "\1\11\3\0\2\11\5\0\1\11\5\0\5\11\1\0"+
    "\13\11\1\122\1\0\1\11\5\0\1\11\3\0\2\11"+
    "\5\0\1\11\5\0\1\11\1\123\3\11\1\0\11\11"+
    "\1\124\2\11\1\0\1\11\5\0\1\11\3\0\2\11"+
    "\5\0\1\11\5\0\5\11\1\0\4\11\1\125\7\11"+
    "\1\0\1\11\5\0\1\11\3\0\2\11\5\0\1\126"+
    "\5\0\5\11\1\0\14\11\1\0\1\11\5\0\1\11"+
    "\3\0\2\11\5\0\1\11\5\0\5\11\1\0\1\11"+
    "\1\127\12\11\1\0\1\11\5\0\1\11\3\0\2\11"+
    "\5\0\1\11\5\0\5\11\1\0\3\11\1\130\10\11"+
    "\1\0\1\11\5\0\1\11\3\0\2\11\5\0\1\11"+
    "\5\0\1\11\1\131\3\11\1\0\1\132\4\11\1\133"+
    "\1\11\1\134\4\11\1\0\1\11\5\0\1\11\3\0"+
    "\2\11\5\0\1\11\5\0\5\11\1\0\3\11\1\135"+
    "\10\11\1\0\1\11\5\0\1\11\3\0\2\11\5\0"+
    "\1\11\5\0\5\11\1\0\6\11\1\136\5\11\1\0"+
    "\1\11\5\0\1\11\3\0\2\11\5\0\1\11\5\0"+
    "\5\11\1\0\3\11\1\137\10\11\1\0\1\11\5\0"+
    "\1\11\3\0\2\11\5\0\1\11\5\0\5\11\1\0"+
    "\7\11\1\140\4\11\1\0\1\11\5\0\1\11\3\0"+
    "\2\11\5\0\1\11\5\0\5\11\1\0\14\11\1\0"+
    "\1\11\1\141\4\0\1\11\3\0\2\11\5\0\1\11"+
    "\5\0\4\11\1\142\1\0\14\11\1\0\1\11\5\0"+
    "\1\11\3\0\2\11\5\0\1\11\5\0\5\11\1\0"+
    "\11\11\1\143\2\11\1\0\1\11\5\0\1\11\3\0"+
    "\2\11\5\0\1\11\5\0\3\11\1\144\1\11\1\0"+
    "\14\11\1\0\1\11\5\0\1\11\3\0\2\11\5\0"+
    "\1\11\5\0\3\11\1\145\1\11\1\0\14\11\1\0"+
    "\1\11\5\0\1\11\3\0\2\11\5\0\1\11\5\0"+
    "\2\11\1\146\2\11\1\0\14\11\1\0\1\11\5\0"+
    "\1\11\3\0\2\11\5\0\1\11\5\0\3\11\1\147"+
    "\1\11\1\0\14\11\1\0\1\11\5\0\1\11\3\0"+
    "\2\11\5\0\1\11\5\0\2\11\1\150\2\11\1\0"+
    "\4\11\1\151\7\11\1\0\1\11\5\0\1\11\3\0"+
    "\2\11\5\0\1\11\5\0\5\11\1\0\5\11\1\152"+
    "\6\11\1\0\1\11\5\0\1\11\3\0\2\11\5\0"+
    "\1\11\5\0\4\11\1\153\1\0\14\11\1\0\1\11"+
    "\5\0\1\11\3\0\2\11\5\0\1\11\5\0\5\11"+
    "\1\0\1\11\1\154\12\11\1\0\1\11\5\0\1\11"+
    "\3\0\2\11\5\0\1\155\5\0\5\11\1\0\14\11"+
    "\1\0\1\11\42\0\1\156\2\0\1\157\11\0\1\11"+
    "\3\0\2\11\5\0\1\11\5\0\5\11\1\0\3\11"+
    "\1\160\10\11\1\0\1\11\5\0\1\11\3\0\2\11"+
    "\5\0\1\11\5\0\5\11\1\0\3\11\1\161\10\11"+
    "\1\0\1\11\5\0\1\11\3\0\2\11\5\0\1\162"+
    "\5\0\5\11\1\0\14\11\1\0\1\11\5\0\1\11"+
    "\3\0\2\11\5\0\1\11\5\0\1\163\4\11\1\0"+
    "\14\11\1\0\1\11\5\0\1\11\3\0\2\11\5\0"+
    "\1\11\5\0\2\11\1\164\2\11\1\0\14\11\1\0"+
    "\1\11\5\0\1\11\3\0\2\11\5\0\1\11\5\0"+
    "\3\11\1\165\1\11\1\0\14\11\1\0\1\11\5\0"+
    "\1\11\3\0\2\11\5\0\1\166\5\0\5\11\1\0"+
    "\14\11\1\0\1\11\5\0\1\11\3\0\2\11\5\0"+
    "\1\11\5\0\5\11\1\0\7\11\1\167\4\11\1\0"+
    "\1\11\5\0\1\11\3\0\2\11\5\0\1\11\5\0"+
    "\5\11\1\0\3\11\1\170\10\11\1\0\1\11\5\0"+
    "\1\11\3\0\2\11\5\0\1\11\5\0\5\11\1\0"+
    "\1\11\1\171\12\11\1\0\1\11\30\0\1\172\64\0"+
    "\1\173\13\0\1\11\3\0\2\11\5\0\1\11\5\0"+
    "\5\11\1\0\2\11\1\174\11\11\1\0\1\11\5\0"+
    "\1\11\3\0\2\11\5\0\1\11\5\0\5\11\1\0"+
    "\1\11\1\175\12\11\1\0\1\11\5\0\1\11\3\0"+
    "\2\11\5\0\1\11\5\0\5\11\1\0\6\11\1\176"+
    "\5\11\1\0\1\11\5\0\1\11\3\0\2\11\5\0"+
    "\1\11\5\0\2\11\1\177\2\11\1\0\14\11\1\0"+
    "\1\11\5\0\1\11\3\0\2\11\5\0\1\11\5\0"+
    "\3\11\1\200\1\11\1\0\14\11\1\0\1\11\45\0"+
    "\1\201\24\0\1\202\36\0\1\11\3\0\2\11\5\0"+
    "\1\11\5\0\3\11\1\203\1\11\1\0\14\11\1\0"+
    "\1\11\5\0\1\11\3\0\2\11\5\0\1\11\5\0"+
    "\4\11\1\204\1\0\14\11\1\0\1\11\5\0\1\11"+
    "\3\0\2\11\5\0\1\205\5\0\5\11\1\0\14\11"+
    "\1\0\1\11\30\0\1\206\60\0\1\207\17\0\1\11"+
    "\3\0\2\11\5\0\1\11\5\0\1\210\4\11\1\0"+
    "\14\11\1\0\1\11\5\0\1\11\3\0\2\11\5\0"+
    "\1\11\5\0\5\11\1\0\7\11\1\211\4\11\1\0"+
    "\1\11\31\0\1\212\25\0\1\11\3\0\2\11\5\0"+
    "\1\11\5\0\5\11\1\0\2\11\1\213\11\11\1\0"+
    "\1\11\5\0\1\11\3\0\2\11\5\0\1\11\5\0"+
    "\2\11\1\214\2\11\1\0\14\11\1\0\1\11\5\0"+
    "\1\11\3\0\2\11\5\0\1\215\5\0\5\11\1\0"+
    "\14\11\1\0\1\11\1\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  9,  1,  9,  1,  1,  1,  1,  1,  9,  9,  9,  9,  1,  9, 
     9,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  9,  0,  0,  9,  0,  1,  1,  9,  9,  9,  1,  1,  1,  1,  1, 
     1,  1,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,  1,  1,  1,  1,  1, 
     0,  0,  1,  1,  1,  0,  9,  1,  1,  9,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
	

    public Lexer(ComplexSymbolFactory sf, java.io.InputStream is){
		this(is);
        symbolFactory = sf;
    }
	public Lexer(ComplexSymbolFactory sf, java.io.Reader reader){
		this(reader);
        symbolFactory = sf;
    }
    
    private StringBuffer sb;
    private ComplexSymbolFactory symbolFactory;
    private int csline,cscolumn;

    public Symbol symbol(String name, int code){
		return symbolFactory.newSymbol(name, code,
						new Location(yyline+1,yycolumn+1, yychar), // -yylength()
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength())
				);
    }
    public Symbol symbol(String name, int code, String lexem){
	return symbolFactory.newSymbol(name, code, 
						new Location(yyline+1, yycolumn +1, yychar), 
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength()), lexem);
    }
    
    protected void emit_warning(String message){
    	System.out.println("scanner warning: " + message + " at : 2 "+ 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }
    
    protected void emit_error(String message){
    	System.out.println("scanner error: " + message + " at : 2" + 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[4074];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2260) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yychar+= yy_markedPos_l-yy_startRead;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 44: 
          {  return symbolFactory.newSymbol("DO", DO);  }
        case 142: break;
        case 46: 
          {  return symbolFactory.newSymbol("OR", OR);  }
        case 143: break;
        case 48: 
          {  return symbolFactory.newSymbol("TO", TO);  }
        case 144: break;
        case 58: 
          {  return symbolFactory.newSymbol("IF", IF);  }
        case 145: break;
        case 63: 
          {  return symbolFactory.newSymbol("NUMBER_REAL", NUMBER_REAL, Double.parseDouble(yytext()));  }
        case 146: break;
        case 5: 
          {  return symbolFactory.newSymbol("NUMBER_INT", NUMBER_INT, Integer.parseInt(yytext()));  }
        case 147: break;
        case 3: 
        case 4: 
          {                                }
        case 148: break;
        case 134: 
          {  return symbolFactory.newSymbol("SETLINE", SETLINE);  }
        case 149: break;
        case 127: 
          {  return symbolFactory.newSymbol("INTEGER", INTEGER);  }
        case 150: break;
        case 123: 
          {  return symbolFactory.newSymbol("PROGRAM", PROGRAM);  }
        case 151: break;
        case 19: 
          {  return symbolFactory.newSymbol("GREATER", GREATER);  }
        case 152: break;
        case 8: 
        case 20: 
        case 21: 
        case 22: 
        case 23: 
        case 24: 
        case 26: 
        case 27: 
        case 28: 
        case 29: 
        case 30: 
        case 31: 
        case 32: 
        case 39: 
        case 43: 
        case 45: 
        case 47: 
        case 49: 
        case 51: 
        case 52: 
        case 53: 
        case 54: 
        case 55: 
        case 56: 
        case 57: 
        case 59: 
        case 60: 
        case 61: 
        case 62: 
        case 66: 
        case 67: 
        case 68: 
        case 69: 
        case 70: 
        case 71: 
        case 72: 
        case 73: 
        case 75: 
        case 76: 
        case 77: 
        case 78: 
        case 79: 
        case 80: 
        case 84: 
        case 86: 
        case 88: 
        case 89: 
        case 90: 
        case 91: 
        case 93: 
        case 94: 
        case 95: 
        case 97: 
        case 98: 
        case 99: 
        case 100: 
        case 102: 
        case 103: 
        case 104: 
        case 106: 
        case 107: 
        case 108: 
        case 114: 
        case 115: 
        case 117: 
        case 118: 
        case 119: 
        case 124: 
        case 125: 
        case 126: 
        case 130: 
        case 131: 
        case 135: 
        case 136: 
        case 139: 
          {  return symbolFactory.newSymbol("ID", ID, yytext());  }
        case 153: break;
        case 40: 
          {  return symbolFactory.newSymbol("LESSERE", LESSERE);  }
        case 154: break;
        case 112: 
          {  return symbolFactory.newSymbol("WHILE", WHILE);  }
        case 155: break;
        case 111: 
          {  return symbolFactory.newSymbol("WRITE", WRITE);  }
        case 156: break;
        case 105: 
          {  return symbolFactory.newSymbol("ENDIF", ENDIF);  }
        case 157: break;
        case 101: 
          {  return symbolFactory.newSymbol("ENDDO", ENDDO);  }
        case 158: break;
        case 33: 
          {  return symbolFactory.newSymbol("COMMA", COMMA);  }
        case 159: break;
        case 17: 
          {  return symbolFactory.newSymbol("EQUAL", EQUAL);  }
        case 160: break;
        case 12: 
          {  return symbolFactory.newSymbol("MINUS", MINUS);  }
        case 161: break;
        case 7: 
          {  return symbolFactory.newSymbol("TIMES", TIMES);  }
        case 162: break;
        case 2: 
        case 9: 
        case 25: 
          {  emit_warning("Unrecognized character '" +yytext()+"' -- ignored");  }
        case 163: break;
        case 138: 
          {  return symbolFactory.newSymbol("ENDPROGRAM", ENDPROGRAM);  }
        case 164: break;
        case 50: 
          {  return symbolFactory.newSymbol("ASSIGNMENT", ASSIGNMENT); }
        case 165: break;
        case 13: 
          {  return symbolFactory.newSymbol("MOD", MOD);  }
        case 166: break;
        case 36: 
          {  return symbolFactory.newSymbol("POW", POW);  }
        case 167: break;
        case 64: 
          {  return symbolFactory.newSymbol("NOT", NOT);  }
        case 168: break;
        case 65: 
          {  return symbolFactory.newSymbol("AND", AND);  }
        case 169: break;
        case 74: 
          {  return symbolFactory.newSymbol("FOR", FOR);  }
        case 170: break;
        case 137: 
          {  return symbolFactory.newSymbol("SETCOLOR", SETCOLOR);  }
        case 171: break;
        case 132: 
          {  return symbolFactory.newSymbol("FUNCTION", FUNCTION);  }
        case 172: break;
        case 41: 
          {  return symbolFactory.newSymbol("NOTEQUAL", NOTEQUAL);  }
        case 173: break;
        case 42: 
          {  return symbolFactory.newSymbol("GREATERE", GREATERE);  }
        case 174: break;
        case 140: 
          {  return symbolFactory.newSymbol("ENDFUNCTION", ENDFUNCTION);  }
        case 175: break;
        case 92: 
          {  return symbolFactory.newSymbol("ELSE", ELSE);  }
        case 176: break;
        case 87: 
          {  return symbolFactory.newSymbol("MOVE", MOVE);  }
        case 177: break;
        case 10: 
          {  return symbolFactory.newSymbol("SEMI", SEMI);  }
        case 178: break;
        case 11: 
          {  return symbolFactory.newSymbol("PLUS", PLUS);  }
        case 179: break;
        case 81: 
          {  return symbolFactory.newSymbol("DRAW", DRAW);  }
        case 180: break;
        case 82: 
          {  return symbolFactory.newSymbol("READ", READ);  }
        case 181: break;
        case 83: 
          {  return symbolFactory.newSymbol("REAL", REAL);  }
        case 182: break;
        case 85: 
          {  return symbolFactory.newSymbol("THEN", THEN);  }
        case 183: break;
        case 120: 
          {  return symbolFactory.newSymbol("STRING", STRING);  }
        case 184: break;
        case 116: 
          {  return symbolFactory.newSymbol("ENDFOR", ENDFOR);  }
        case 185: break;
        case 113: 
          {  return symbolFactory.newSymbol("RETURN", RETURN);  }
        case 186: break;
        case 18: 
          {  return symbolFactory.newSymbol("LESSER", LESSER);  }
        case 187: break;
        case 16: 
          {  return symbolFactory.newSymbol("RPAREN", RPAREN);  }
        case 188: break;
        case 15: 
          {  return symbolFactory.newSymbol("LPAREN", LPAREN);  }
        case 189: break;
        case 14: 
          {  return symbolFactory.newSymbol("UMINUS", UMINUS);  }
        case 190: break;
        case 6: 
          {  return symbolFactory.newSymbol("DIVIDE", DIVIDE);  }
        case 191: break;
        case 38: 
          {  return symbolFactory.newSymbol("STRINGLITERAL", STRINGLITERAL, yytext());  }
        case 192: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              {     return symbolFactory.newSymbol("EOF",sym.EOF);
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
