
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 7;
  public static final int POW = 8;
  public static final int FUNCTION = 23;
  public static final int ASSIGNMENT = 26;
  public static final int UMINUS = 5;
  public static final int COMMENT = 27;
  public static final int INTEGER = 37;
  public static final int NOTEQUAL = 16;
  public static final int LPAREN = 10;
  public static final int GREATER = 18;
  public static final int SEMI = 2;
  public static final int ENDDO = 45;
  public static final int FOR = 46;
  public static final int MINUS = 4;
  public static final int WRITE = 32;
  public static final int RPAREN = 11;
  public static final int DRAW = 31;
  public static final int NOT = 15;
  public static final int AND = 13;
  public static final int ENDFUNCTION = 24;
  public static final int OR = 14;
  public static final int COMMA = 28;
  public static final int SETLINE = 34;
  public static final int ENDFOR = 48;
  public static final int ENDPROGRAM = 22;
  public static final int LESSER = 17;
  public static final int PLUS = 3;
  public static final int IF = 39;
  public static final int ID = 51;
  public static final int EOF = 0;
  public static final int RETURN = 25;
  public static final int EQUAL = 12;
  public static final int error = 1;
  public static final int PROGRAM = 21;
  public static final int GREATERE = 20;
  public static final int MOD = 9;
  public static final int REAL = 38;
  public static final int MOVE = 30;
  public static final int TIMES = 6;
  public static final int SETCOLOR = 33;
  public static final int LESSERE = 19;
  public static final int ENDIF = 42;
  public static final int ELSE = 41;
  public static final int READ = 29;
  public static final int TO = 47;
  public static final int WHILE = 43;
  public static final int CLEAR = 35;
  public static final int THEN = 40;
  public static final int NUMBER_REAL = 50;
  public static final int STRING = 36;
  public static final int STRINGLITERAL = 52;
  public static final int DO = 44;
  public static final int NUMBER_INT = 49;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "UMINUS",
  "TIMES",
  "DIVIDE",
  "POW",
  "MOD",
  "LPAREN",
  "RPAREN",
  "EQUAL",
  "AND",
  "OR",
  "NOT",
  "NOTEQUAL",
  "LESSER",
  "GREATER",
  "LESSERE",
  "GREATERE",
  "PROGRAM",
  "ENDPROGRAM",
  "FUNCTION",
  "ENDFUNCTION",
  "RETURN",
  "ASSIGNMENT",
  "COMMENT",
  "COMMA",
  "READ",
  "MOVE",
  "DRAW",
  "WRITE",
  "SETCOLOR",
  "SETLINE",
  "CLEAR",
  "STRING",
  "INTEGER",
  "REAL",
  "IF",
  "THEN",
  "ELSE",
  "ENDIF",
  "WHILE",
  "DO",
  "ENDDO",
  "FOR",
  "TO",
  "ENDFOR",
  "NUMBER_INT",
  "NUMBER_REAL",
  "ID",
  "STRINGLITERAL"
  };
}

